//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blood_Test
    {
        public int id { get; set; }
        public string disease { get; set; }
        public string idDonationCenter { get; set; }
        public int idDonation { get; set; }
    
        public virtual Blood_Donation Blood_Donations { get; set; }
        public virtual Donation_Center Donation_Centers { get; set; }
    }
}
