//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blood_Donation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blood_Donation()
        {
            this.Blood_Tests = new HashSet<Blood_Test>();
        }
    
        public int idDonation { get; set; }
        public string bloodGroup { get; set; }
        public bool isApproved { get; set; }
        public System.DateTime donationDate { get; set; }
        public System.DateTime expiratonDate { get; set; }
        public string idDonationCenter { get; set; }
        public string idDonor { get; set; }
        public int idPatient { get; set; }
        public string componentName { get; set; }
        public int quantity { get; set; }
        public string status { get; set; }
    
        public virtual Donation_Center Donation_Centers { get; set; }
        public virtual Donor Donor { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blood_Test> Blood_Tests { get; set; }
    }
}
