//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int idMessage { get; set; }
        public string msg { get; set; }
        public string idPerson { get; set; }
        public string idDonationCenter { get; set; }
    
        public virtual Donation_Center Donation_Centers { get; set; }
        public virtual Donor Donor { get; set; }
    }
}
