//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public string email { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string gender { get; set; }
        public string phoneNr { get; set; }
        public System.DateTime birthdate { get; set; }
        public string password { get; set; }
        public string bloodGroup { get; set; }
        public int idCity { get; set; }
        public string address { get; set; }
        public string actualAddress { get; set; }
        public int idActualCity { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Donor Donor { get; set; }
        public virtual Location Location { get; set; }
    }
}
